{{- if (not .ephemeral) }}
{{-   $fontDir := "" }}
{{-   $baseURL := "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}
["{{ $fontDir }}/JetBrainsMonoNerdFontMono-Regular.ttf"]
    type = "file"
    url = "{{ $baseURL }}Regular/JetBrainsMonoNerdFontMono-Regular.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/JetBrainsMonoNerdFontMono-Bold.ttf"]
    type = "file"
    url = "{{ $baseURL }}Bold/JetBrainsMonoNerdFontMono-Bold.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/JetBrainsMonoNerdFontMono-Italic.ttf"]
    type = "file"
    url = "{{ $baseURL }}Italic/JetBrainsMonoNerdFontMono-Italic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/JetBrainsMonoNerdFontMono-BoldItalic.ttf"]
    type = "file"
    url = "{{ $baseURL }}BoldItalic/JetBrainsMonoNerdFontMono-BoldItalic.ttf"
    refreshPeriod = "168h"
{{- end }}
