{{- if (not .ephemeral) }}
{{-   $fontDir := "" }}
{{-   $baseURL := "https://raw.githubusercontent.com/LuarRaNa/dotfiles/main/assets/Archive.zip" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}
["{{ $fontDir }}"]
    type = "archive"
    url = "{{ $baseURL }}"
    refreshPeriod = "168h"
    include = [
        "IosevkaCustom-Bold.ttf",
        "IosevkaCustom-BoldOblique.ttf",
        "IosevkaCustom-Oblique.ttf",
        "IosevkaCustom-Regular.ttf"
    ]
{{- end }}
