{{- if (not .ephemeral) }}
{{-   $fontDir := "" }}
{{-   $baseURL := output "curl" "-s" "https://api.github.com/repos/be5invis/Iosevka/releases/latest" | fromJson | jq ".assets | .[] | select(.name | startswith(\"PkgTTF-Unhinted-IosevkaFixed-\")) | .browser_download_url" | first}}
{{-   $baseURL2 := "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf"}}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}
["{{ $fontDir }}"]
    type = "archive"
    url = "{{ $baseURL }}"
    refreshPeriod = "168h"
    include = [
        "IosevkaFixed-ExtendedBold.ttf",
        "IosevkaFixed-ExtendedBoldOblique.ttf",
        "IosevkaFixed-Extended.ttf",
        "IosevkaFixed-ExtendedOblique.ttf"
    ]
["{{ $fontDir }}/SymbolsNerdFontMono-Regular.ttf"]
    type = "file"
    url = "{{ $baseURL2 }}"
    refreshPeriod = "168h"
{{- end }}
