theme = "dark_plus"

[editor]
rulers = [80, 120]

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"

[editor.lsp]
display-messages = true

[editor.whitespace]
render = "all"
