theme = "everforest_dark"

[editor]
auto-save = true
bufferline = "always"
cursorline = true
color-modes = true

[editor.file-picker]
hidden = false
parents = false

[editor.indent-guides]
render = true
character = "╎"

[editor.lsp]
display-messages = true

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
left = [
  "mode",
  # "version-control",
  "spinner",
  "diagnostics",
  "workspace-diagnostics",
  "file-name",
]
center = []
right = [
  "selections",
  "primary-selection-length",
  "position",
  "total-line-numbers",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "│"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "␣"
nbsp = "␣"
tab = "␉"
newline = "␤"
tabpad = "␣"

[editor.soft-wrap]
enable = true
wrap-indicator = "␊"
