theme = "rose_pine_dawn"

[editor]
rulers = [80, 120]
auto-save = true
bufferline = "always"

[editor.file-picker]
hidden = false
parents = false

[editor.indent-guides]
render = true
character = "╎"

[editor.lsp]
display-messages = true

[editor.statusline]
left = [
  "mode",
  "version-control",
  "spinner",
  "diagnostics",
  "workspace-diagnostics"
]
center = ["file-name"]
right = [
  "selections",
  "primary-selection-length",
  "position",
  "position-percentage",
  "total-line-numbers",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "│"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "␣"
nbsp = "␣"
tab = "␉"
newline = "␤"
tabpad = "␣" # Tabs will look like "␉···" (depending on tab width)

[editor.soft-wrap]
enable = true
wrap-indicator = "␊"
