theme = "rose_pine_dawn"

[editor]
auto-save = true
bufferline = "always"
cursorline = true
undercurl = true
color-modes = true
text-width = 100
rulers = [80, 100]

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
left = [
  "mode",
  "spinner",
  "diagnostics",
  "workspace-diagnostics",
  "file-name",
]
center = []
right = [
  "selections",
  "primary-selection-length",
  "position",
  "total-line-numbers",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "│"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "·"
tab = "␉"
newline = "␤"
tabpad = "·"

[editor.soft-wrap]
enable = true
max-indent-retain = 50
max-wrap = 0
wrap-indicator = ""
wrap-at-text-width = true
