add_newline = false

continuation_prompt = ""

format = """
$username\
$directory\
$git_branch\
$docker_context\
$character\
"""

[username]
show_always = true
format = "[$user IN ](bold cyan)"

[directory]
home_symbol = "HOME"
format = "[$path ](bold white)"

[git_branch]
style = "bold blue"
symbol = "BRANCH "
format = "[\nON $symbol$branch(:$remote_branch) ]($style)"

[docker_context]
symbol = "DOCKER "
style = "bold purple"
format = "[\nVIA $symbol$context ]($style)"

[character]
success_symbol = ""
error_symbol = ""
format = "[$symbol\n](hidden)"

[package]
disabled = true

[battery]
disabled = true
