add_newline = false

continuation_prompt = ""

format = """
$username\
$directory\
$git_branch\
$character\
$line_break
"""

[username]
show_always = true
format = "[|](8)[USER IN ](bold)"

[directory]
home_symbol = "HOME"
format = "[$path ](bold)"

[git_branch]
style = "bold"
symbol = "BRANCH "
format = "[ON $symbol$branch(:$remote_branch) ]($style)"

[package]
disabled = true

[battery]
disabled = true

[character]
success_symbol = ""
error_symbol = ""
vicmd_symbol = ""
format = "[$symbol](bold)"
